base: baseline_claim_evidence_deberta_v3_fever.yaml

experiment:
  name: baseline_claim_evidence_deberta_v3_fever_symmetric

data:
  test_path: data/FEVER/converted_data/symmetric.json

outputs:
  prediction_dir: outputs/FEVER/deberta_v3/baselines/claim_evidence/predictions/symmetric
