base: baseline_claim_evidence_fever.yaml

experiment:
  name: baseline_claim_evidence_symmetric_fever

data:
  test_path: data/FEVER/converted_data/symmetric.json

outputs:
  prediction_dir: outputs/FEVER/baselines/claim_evidence/predictions/symmetric_fever
