base: baseline_claim_only_fever.yaml

experiment:
  name: baseline_claim_only_symmetric_fever

data:
  test_path: data/FEVER/converted_data/symmetric.json

outputs:
  prediction_dir: outputs/FEVER/baselines/claim_only/predictions/symmetric_fever
